name: Exploit
description: You have found a major exploit that needs fixing urgently. Please note if this is a serious issue which can be abused, please DM @luisc99 on Discord and report it privately. Thank you
title: "<title>"
labels: ["exploit"]
assignees: ["luisc99"]
body:
- type: textarea
  attributes:
    label: Description
    description: A clear description of what the exploit is
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A brief description of what you expected to happen instead
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Try to explain clearly how you found this exploit, and how we can reproduce it
    placeholder: |
      1. I was in...
      1. I was doing...
      1. Then I did...
      1. Then ... happened
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
