name: Feature Request
description: You have an idea for a new feature you'd like to see added
title: "<title>"
labels: ["feature-request"]
assignees: ["luisc99"]
body:
- type: textarea
  attributes:
    label: Description
    description: A clear description of what your suggestion is, and what you'd like to see from it
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives
    description: Describe any alternatives to the new feature, including what can currently be done on the server, and say why these are unsuitable
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the feature you are requesting

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
